// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD--0RkJrPiHawhhQVhyvR97BtFRDYX4t0',
    appId: '1:706411758112:android:7cd4662556892210ea7245',
    messagingSenderId: '706411758112',
    projectId: 'uberdriver-9cfcf',
    databaseURL: 'https://uberdriver-9cfcf-default-rtdb.firebaseio.com',
    storageBucket: 'uberdriver-9cfcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Dh4gI4-GFarD8nkgWsIjFzc3oy-mxeI',
    appId: '1:706411758112:ios:2e929249171d5034ea7245',
    messagingSenderId: '706411758112',
    projectId: 'uberdriver-9cfcf',
    databaseURL: 'https://uberdriver-9cfcf-default-rtdb.firebaseio.com',
    storageBucket: 'uberdriver-9cfcf.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );
}
